name: Android Unit Tests

on: [ push, workflow_dispatch]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run unit tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        target: default
        arch: x86_64
        profile: pixel
        script: ./gradlew connectedCheck --stacktrace
